<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20825" started-at="2015-11-19T20:55:52Z" finished-at="2015-11-19T20:56:13Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20825" started-at="2015-11-19T20:55:52Z" finished-at="2015-11-19T20:56:13Z">
      <class name="com.bfs.report.MultiTestReport">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.bfs.report.MultiTestReport@6df97b55]" name="beforeTest" is-config="true" duration-ms="109" started-at="2015-11-19T15:55:52Z" finished-at="2015-11-19T15:55:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="verifyBlogTitle()[pri:0, instance:com.bfs.report.MultiTestReport@6df97b55]" name="verifyBlogTitle" duration-ms="10857" started-at="2015-11-19T15:55:52Z" finished-at="2015-11-19T15:56:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.bfs.report.MultiTestReport.verifyBlogTitle(MultiTestReport.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyBlogTitle -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.bfs.report.MultiTestReport@6df97b55]" name="tearDown" is-config="true" duration-ms="1581" started-at="2015-11-19T15:56:03Z" finished-at="2015-11-19T15:56:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyBlogTitle status=FAILURE method=MultiTestReport.verifyBlogTitle()[pri:0, instance:com.bfs.report.MultiTestReport@6df97b55] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="verifyURL()[pri:0, instance:com.bfs.report.MultiTestReport@6df97b55]" name="verifyURL" duration-ms="8215" started-at="2015-11-19T15:56:05Z" finished-at="2015-11-19T15:56:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyURL -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.bfs.report.MultiTestReport@6df97b55]" name="tearDown" is-config="true" duration-ms="25" started-at="2015-11-19T15:56:13Z" finished-at="2015-11-19T15:56:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyURL status=SUCCESS method=MultiTestReport.verifyURL()[pri:0, instance:com.bfs.report.MultiTestReport@6df97b55] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.bfs.report.MultiTestReport@6df97b55]" name="afterTest" is-config="true" duration-ms="30" started-at="2015-11-19T15:56:13Z" finished-at="2015-11-19T15:56:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.bfs.report.MultiTestReport -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
